
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Sadman
 */
public class Admin_registrationpage extends javax.swing.JFrame {

    /**
     * Creates new form Admin_registrationpage
     */
    public Admin_registrationpage() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        sdfsf = new javax.swing.JLabel();
        dfgdg = new javax.swing.JLabel();
        dfgdfgd = new javax.swing.JLabel();
        dfsdfsdf = new javax.swing.JLabel();
        passtf = new javax.swing.JPasswordField();
        conpasstf = new javax.swing.JPasswordField();
        signupbutton = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        emailtf = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        idtf = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        coursetf = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel3.setBackground(new java.awt.Color(97, 212, 195));

        jLabel7.setFont(new java.awt.Font("Comic Sans MS", 0, 36)); // NOI18N
        jLabel7.setText("Welcome to ");

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 0, 36)); // NOI18N
        jLabel1.setText("Admin registration section");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(122, 122, 122)
                        .addComponent(jLabel7)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(379, 379, 379)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(36, 47, 65));

        jLabel2.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Sign up");

        sdfsf.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        sdfsf.setForeground(new java.awt.Color(255, 255, 255));
        sdfsf.setText("User Id");

        dfgdg.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        dfgdg.setForeground(new java.awt.Color(255, 255, 255));
        dfgdg.setText("Course No");

        dfgdfgd.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        dfgdfgd.setForeground(new java.awt.Color(255, 255, 255));
        dfgdfgd.setText("Password");

        dfsdfsdf.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        dfsdfsdf.setForeground(new java.awt.Color(255, 255, 255));
        dfsdfsdf.setText("Confirm Password");

        passtf.setBackground(new java.awt.Color(36, 47, 65));
        passtf.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        passtf.setForeground(new java.awt.Color(255, 255, 255));
        passtf.setBorder(null);
        passtf.setDisabledTextColor(new java.awt.Color(204, 204, 204));
        passtf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passtfActionPerformed(evt);
            }
        });

        conpasstf.setBackground(new java.awt.Color(36, 47, 65));
        conpasstf.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        conpasstf.setForeground(new java.awt.Color(255, 255, 255));
        conpasstf.setBorder(null);
        conpasstf.setDisabledTextColor(new java.awt.Color(204, 204, 204));

        signupbutton.setBackground(new java.awt.Color(97, 212, 195));
        signupbutton.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        signupbutton.setText("Sign up");
        signupbutton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                signupbuttonMouseClicked(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("E-mail");

        emailtf.setBackground(new java.awt.Color(36, 47, 65));
        emailtf.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        emailtf.setForeground(new java.awt.Color(255, 255, 255));
        emailtf.setBorder(null);
        emailtf.setDisabledTextColor(new java.awt.Color(204, 204, 204));
        emailtf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailtfActionPerformed(evt);
            }
        });

        jSeparator1.setForeground(new java.awt.Color(255, 255, 255));

        idtf.setBackground(new java.awt.Color(36, 47, 65));
        idtf.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        idtf.setForeground(new java.awt.Color(255, 255, 255));
        idtf.setBorder(null);
        idtf.setDisabledTextColor(new java.awt.Color(204, 204, 204));
        idtf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idtfActionPerformed(evt);
            }
        });

        jSeparator2.setForeground(new java.awt.Color(255, 255, 255));

        coursetf.setBackground(new java.awt.Color(36, 47, 65));
        coursetf.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        coursetf.setForeground(new java.awt.Color(255, 255, 255));
        coursetf.setBorder(null);
        coursetf.setDisabledTextColor(new java.awt.Color(204, 204, 204));
        coursetf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                coursetfActionPerformed(evt);
            }
        });

        jSeparator3.setForeground(new java.awt.Color(255, 255, 255));

        jSeparator4.setForeground(new java.awt.Color(255, 255, 255));

        jSeparator5.setForeground(new java.awt.Color(255, 255, 255));

        jButton1.setBackground(new java.awt.Color(97, 212, 195));
        jButton1.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        jButton1.setText("Back");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(112, 112, 112)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jSeparator5, javax.swing.GroupLayout.DEFAULT_SIZE, 363, Short.MAX_VALUE)
                    .addComponent(jSeparator4)
                    .addComponent(coursetf)
                    .addComponent(jSeparator1)
                    .addComponent(jLabel3)
                    .addComponent(dfsdfsdf)
                    .addComponent(dfgdg)
                    .addComponent(dfgdfgd)
                    .addComponent(jLabel2)
                    .addComponent(passtf)
                    .addComponent(conpasstf)
                    .addComponent(signupbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(emailtf, javax.swing.GroupLayout.DEFAULT_SIZE, 363, Short.MAX_VALUE)
                    .addComponent(sdfsf)
                    .addComponent(idtf)
                    .addComponent(jSeparator2)
                    .addComponent(jSeparator3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 177, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(108, 108, 108)
                .addComponent(jLabel2)
                .addGap(48, 48, 48)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(emailtf, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(sdfsf)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(idtf, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dfgdg)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(coursetf, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dfgdfgd)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(passtf, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dfsdfsdf)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(conpasstf, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(75, 75, 75)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(signupbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(106, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void signupbuttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_signupbuttonMouseClicked
       String email=emailtf.getText();
       String userid=idtf.getText();
       String course=coursetf.getText();
       String pass=passtf.getText();
       String conpass=conpasstf.getText();
       if(email.equals("") || userid.equals("") || course.equals("") || pass.equals("") ||  conpass.equals(""))
       {
           JOptionPane.showMessageDialog(null, "Must fill up al the required fields");
       }
       else{
       try{
          database_connection dc=new database_connection(); 
          String q = "insert into teacher_info values('"+email+"','"+userid+"','"+course+"','"+pass+"','"+conpass+"')";
          dc.state.executeUpdate(q);
          JOptionPane.showMessageDialog(null, "Successful");
          setVisible(false);
          new Admin_loginpage().setVisible(true);
           }
       catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
       }
       }                                         

    }//GEN-LAST:event_signupbuttonMouseClicked

    private void coursetfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_coursetfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_coursetfActionPerformed

    private void passtfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passtfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passtfActionPerformed

    private void emailtfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailtfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailtfActionPerformed

    private void idtfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idtfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idtfActionPerformed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
       this.setVisible(false);
       new Admin_loginpage().setVisible(true);
    }//GEN-LAST:event_jButton1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Admin_registrationpage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField conpasstf;
    private javax.swing.JTextField coursetf;
    private javax.swing.JLabel dfgdfgd;
    private javax.swing.JLabel dfgdg;
    private javax.swing.JLabel dfsdfsdf;
    private javax.swing.JTextField emailtf;
    private javax.swing.JTextField idtf;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JPasswordField passtf;
    private javax.swing.JLabel sdfsf;
    private javax.swing.JButton signupbutton;
    // End of variables declaration//GEN-END:variables
}
